up = keyboard_check_pressed(vk_up)
down = keyboard_check_pressed(vk_down)
right_hold = keyboard_check(vk_right)
left_hold = keyboard_check(vk_left)
right = keyboard_check_pressed(vk_right)
left = keyboard_check_pressed(vk_left)
confirm = keyboard_check_pressed(vk_enter)
click = device_mouse_check_button_pressed(0,mb_left)